#!/bin/bash
app=$1; config=$2; log=$3;

RBENV_DIR="/usr/local/rbenv"
if [ -d "${RBENV_DIR}" ]; then
	export RBENV_ROOT="${RBENV_DIR}"
	export PATH="${RBENV_ROOT}/bin:${PATH}"
	eval "$(rbenv init -)"
else
  echo "Error: rbenv directory does not exist: ${RBENV_DIR}" && exit 1
fi

cd $app && exec bundle exec puma -C $config 2>&1 >> $log
exit 0
